all: QtUiSources MocStage ResourcesStage

QtUiSources : mainwindow_ui.h MainWindow.cpp

mainwindow_ui.h: mainwindow.ui
	uic -o mainwindow_ui.h mainwindow.ui

MainWindow.cpp : mainwindow_ui.h
	touch MainWindow.cpp
    
MocStage : moc_MainWindow.cpp

moc_MainWindow.cpp : MainWindow.h
	moc -o moc_MainWindow.cpp MainWindow.h
    
ResourcesStage : rc_icons.cpp

rc_icons.cpp : icons.qrc
	rcc -o rc_icons.cpp icons.qrc

clean:
	rm rc_icons.cpp moc_MainWindow.cpp mainwindow_ui.h

